### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by Kerotos** [maximumstock/poe-currency-flip-planner#13]
So just found this and i have no idea at all how to use it. I never used Python and and step by step or video guide would help.

**Comment by maximumstock** [comment]
Hi Kerotos,

well first of all you need Python (version 3.7 or above) and a way to execute Python scripts. So make sure you have a recent version of Python installed. Then you can fetch the repository (via clone or download) and run it via the command line. How exactly this looks depends on your operating system and setup.
