### ISSUE TITLE
Update default data backend to official PoE trade forum

### ISSUE THREAD

**Issue by michaelobr** [maximumstock/poe-currency-flip-planner#15]
This league the default PoE trade forum https://pathofexile.com/trade appears to be operating faster than poe.trade. I'd recommend updating the default backend. 

If you don't wish to do so, could you please provide what we should set the backend variable equal to in line 74 of cli.py? 

Thanks.

**Comment by rbriank** [comment]
I don't believe it's as simple as changing that line.  Look at the code is scr/backends - there's only the poetrade version currently available.  It would mean writing a new adapter that can talk to something else - ie. the official trade site.  There's probably some similarity, but I'm not familiar enough with it to know what that would be.

**Comment by rbriank** [comment]
Poking around the exchange site (want, have), it seems quite different.  Everything is encoded in the URL vs. having parameters.  Not sure how those seach URLs are generated. Anyone know?

**Comment by maximumstock** [comment]
Thanks for bringing this up, I'm not too involved with PoE right now as I recently started working. 

In the past, I already had a client for the official PoE trade site. The official trading site imposes a rate limit, which was detrimental for my scraping needs back then, so I removed its backend implementation to simplify everything. But if it might be beneficial to you guys then I'll restore it from earlier commits.

**Comment by rbriank** [comment]
Yes, please!

**Comment by maximumstock** [comment]
So I am back at a working version for both poe.trade and the official Path of Exile trading site. Here are two screenshots that show the needed time to fetch all the data from the respective backend:

## poe.trade
![poe trade](https://user-images.githubusercontent.com/9075718/71927586-11b2b000-3196-11ea-99b5-f5d33cedd863.png)
## Path of Exile Trading
![poeofficial](https://user-images.githubusercontent.com/9075718/71927589-12e3dd00-3196-11ea-9097-0f2de0965ec6.png)

Losing time during fetching is probably the most critical problem for this whole tool to work right now, so I think you should keep using poe.trade :)

**Comment by zombodotcom** [comment]
Did you transfer it to pathofexile trade? Try poeapp for science

**Comment by maximumstock** [comment]
@zombodotcom I just tried it. It imposes a rate-limit as well, which of course is a sensible choice for an API as they offer it. The only way to make data retrieval faster than poe.trade is to collect the public stash tab API data myself, but that is far out of the scope of this project.

**Comment by zombodotcom** [comment]
Yeah doing poe.ninja style work or gathering that much data isn't worth it. There's issues with poe.trade
 And pathnof exile trade all the time . Your solution is fine. You can't fix their libraries basically
