### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by Gwenillia** [maximumstock/poe-currency-flip-planner#16]
Hey, 

I just wanted to try this out but. The cli.py work.

But I can't run the .sh. 

Thank you ^^"

**Comment by maximumstock** [comment]
So `run_collector.sh` is only meant for my personal scraping which I use for everything in the `data_analysis` folder. If you are interested in that, you probably have to make the script executable on your machine, which you can do on the command line (assuming you are running bash or some kind of Unix shell) with `chmod +x run_collector.sh`.

`sync_server.sh` is only meant for my personal setup and not needed for anything you want to do.

**Comment by Gwenillia** [comment]
Okej, Perfect then, thanks.
