### ISSUE TITLE
Cli.py Error

### ISSUE THREAD

**Issue by C4RP3N0CT3M** [maximumstock/poe-currency-flip-planner#160]
I keep getting an error with the latest repository (cmd cli.py), even when using no arguments.
![2020-05-01 11_38_28-C__Windows_System32_cmd exe - pipenv  shell](https://user-images.githubusercontent.com/58274597/80818406-1b2ab280-8ba1-11ea-98c4-dfb8846447eb.png)

**Comment by maximumstock** [comment]
Oh well, seems I shouldn't do releases right after midnight :) I'll fix it right away

**Comment by C4RP3N0CT3M** [comment]
> Oh well, seems I shouldn't do releases right after midnight :) I'll fix it right away

No worries lol. I'm also seeing issues with the filtering. If I use a currency filter, it says that it can't find any pairs, but can find pairs for that same currency without the filter for example.

**Comment by maximumstock** [comment]
@C4RP3N0CT3M I fixed the crashing bug for now in 0.3.1, but I'm not 100% sure what you mean with the second filter issue.

**Comment by C4RP3N0CT3M** [comment]
@maximumstock let me start with a fresh install. I tried to fix it myself, and probably messed something up.
