### ISSUE TITLE
Get around poe/trade official rate limit with Poe session is?

### ISSUE THREAD

**Issue by rbriank** [maximumstock/poe-currency-flip-planner#17]
I saw this mentioned in a thread on Reddit - getting the session if from the logged browser session as a way to get around the rate limit.

Can you add it as a an arg to cli.py and pass it along?

**Comment by maximumstock** [comment]
According to [1](https://www.pathofexile.com/forum/view-thread/2079853),[2](https://www.reddit.com/r/pathofexiledev/comments/7xw0cl/trade_api_cors_and_rate_limiting/?st=k57z4xpf&sh=24627bef), that would at most double the rate-limit for a given IP address. And that only works if you have two accounts and two session ids. Can you check if this matches your source?

Even if that works, cutting the fetching time in half is still not enough to be as fast as poe.trade.
The really only fastest way is to use your own stash tab API indexer.

**Comment by rbriank** [comment]
I read this yesterday:
https://www.reddit.com/r/pathofexile/comments/emh24g/oops_we_are_also_working_on_a_trademacro_clone/

But based on your links, it may not be factual. Unless they've changed how
it works since those were posted?

**Comment by rbriank** [comment]
I've also seen in some of the trade helpers, you can have up to 80
concurrent connections, would that be a way to speed things up? Although,
one streamer was saying that going over 40 seemed problematic. Hard to say
if that was a hardware or bandwidth issue for him specifically.

**Comment by rbriank** [comment]
Amazing! Thank you.

**Comment by maximumstock** [comment]
@rbriank Should be much faster now :) See https://github.com/maximumstock/poe-currency-flip-planner/releases/tag/0.1

**Comment by rbriank** [comment]
Amazing! Thanks again.
