### ISSUE TITLE
How to use pathfinder.py as external lib?

### ISSUE THREAD

**Issue by mikeboy91** [maximumstock/poe-currency-flip-planner#211]
Hey I want to use this in my own small project. I just want to output the cli stuff on a website and let Flask expose an API and the API-endpoint call pathfinder.run().
I managed to get my setup rdy and imported your project as git submodule in its own folder within the project.
However it seems to mess up everything with the absolute paths.

```
client
  client stuff
server
  app.py (calls pathfinder.py)
  poecfp (your project as git submodule)
    cli.py
    src
      pathfinder.py
      ...
```

When I run everything, your `commons.py` says `No such file or directory: 'config/excluded_traders.txt'`

I just don't know, how to do it properly. Maybe you can give me an advise on how to use your pathfinder.py as an external 3rd party lib in my own project.

EDIT: btw I used Docker to setup everything. So i have NOT used any python virtual environments.

**Comment by maximumstock** [comment]
Hey there, I'll look into it, but cannot guarantee an answer for the next two days.

**Comment by mikeboy91** [comment]
I think it would help to do something like this `default_path = os.path.dirname(os.path.abspath(__file__)) + "/../config/excluded_traders.txt"`

At least it works for me and should work with your stand alone setup.

**Comment by maximumstock** [comment]
Afaik if you only import `pathfinder.py`, there shouldnt be any path dependencies on any file, as all of those are added via `Pathfinder.__init__`.

**Comment by maximumstock** [comment]
Sorry for my confusion, I your submodule-setup myself and fixed it with your fix from above in https://github.com/maximumstock/poe-currency-flip-planner/commit/0bc6d569e9e36ec761939fc266b18c8e223b3a46. Thanks for reaching out!
