### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by Roeksw** [maximumstock/poe-currency-flip-planner#214]
I tried to install your 'poe-currency-flip-planner'  using Kali Linux, did according to the instructions, but when entering  `pip install -r requirements.txt` return error.  I on Win 10, python is installed. I attached the part of the output where the error appears.
[error.txt](https://github.com/maximumstock/poe-currency-flip-planner/files/4907005/error.txt)

**Comment by maximumstock** [comment]
Hmm, seems like something about your Python installation is broken. Did a quick google search of some of your errors. Maybe try `pip install wheel` to get rid of the `invalid command 'bdist_wheel'`errors. Other than that I cannot really help you, as this is not related to my tool.
