### ISSUE TITLE
[Idea] - get top items from poe.ninja API to automatically search for potential flips

### ISSUE THREAD

**Issue by CayoM** [maximumstock/poe-currency-flip-planner#260]
would be nice to have an automated flip inventory coming from poe.ninja trending items or hidden champions.

https://poe.ninja/swagger/index.html

im willing to help out on the project also. If there is any interest, please let me know (german speaking here also)

**Comment by maximumstock** [comment]
Hey there, thanks for reaching out!

I'm not entirely sure what you mean by an "automated flip inventory". Could you please elaborate a little further? :)

**Comment by CayoM** [comment]
> Hey there, thanks for reaching out!
> 
> I'm not entirely sure what you mean by an "automated flip inventory". Could you please elaborate a little further? :)

sure, what I mean is, that instead of defining what items to watch in order to flip, we could automate it also using the poe.ninja api to get the top items or any other items.

Here for example we get the top (most expensive) Armours from Heist league:
https://poe.ninja/api/data/itemoverview?league=Heist&type=UniqueArmour

implementing some conditions (for example percentage up to 10% in the last day, etc, etc, etc) we could create a flip list dynamically and pass it to your code.

in my vision, the end goal would be to fetch the items to flip from poe.ninja, than modify the query to the trade-api to filter for those items with an max price below (maybe 20%) the value from poe.ninja. Any match would mean you can whisper the user to flip and the code would also recommend a new price.

i hope i could explain it properly ;-)

**Comment by maximumstock** [comment]
Hmm, I think I see what you mean. 

So, I think what you are describing sounds more like a notification tool, that notifies you when a certain item (or several) become available for sale within a specifiable value range below the current median/mean price. So similar to a live search, but for a lot of items, eg. all unique armour pieces. Did I describe what you are looking for?

**Comment by CayoM** [comment]
yes, thats pretty much it. scrape poe.ninja for currency / items to use as base for what is worth flipping, so you dont have to manage/configure anything besides the item groups (armour, weapons, currency, maps, etc). Everything else is 100% dynamic.

**Comment by maximumstock** [comment]
Hmm, I thought about it and I don't think what you are aiming for is suited for this specific project. I rather think what you describe should be implemented on top of some Stash Tab API indexer. I'm currently working on one, but there are several others here on GitHub, which are probably more feature-complete and easier to extend as of now.
