### ISSUE TITLE
[Idea]: Support adding "trade paths" with vendors

### ISSUE THREAD

**Issue by 1480c1** [maximumstock/poe-currency-flip-planner#282]
One idea I have that I'm not sure if I can immediately find an issue or mention about is using vendors as potential traders

One example would be if there's a disparity between Orbs of Regret to Orbs of Alchemy, such as 1 Chaos to 8 Orbs and 1 Chaos to 7 Alchemies, it would be possible to buy 8 Orbs of regret to sell to a vendor for 1 Alchemy each and sell 7 of those alchemies for 1 chaos

**Comment by maximumstock** [comment]
Hey there,

thanks for reaching out! I had vendor prices on my todo list a while ago but dismissed it because I thought the market would prevent this by pricing outside of the baseline vendor prices. Nevertheless, I'll take a look and report back if I can notice any difference.

**Comment by maximumstock** [comment]
I put up a PR that should technically implement it, but I'll probably add one or two test cases for your case above before merging.

**Comment by maximumstock** [comment]
Ah, I'm very sorry, but it seems like I misunderstood you the first time.

Now I understand that you were talking about unexpected remainders. For example in your specified case above, arriving back at one `Chaos Orb` but also having gained one `Orb of Alchemy` along the way, right? Hmm, I'm gonna look and see what's the best way to incorporate this in the current graph traversal.

**Comment by maximumstock** [comment]
I'll close this since I merged https://github.com/maximumstock/poe-currency-flip-planner/pull/286 to support vendor offers. 

Supporting remainders in the profitability calculation is something I don't have a viable plan for atm and I feel like its out of scope for now.
