### ISSUE TITLE
[Request]: Change the config file through a flag like --config

### ISSUE THREAD

**Issue by 1480c1** [maximumstock/poe-currency-flip-planner#284]
Although I see some code that looks like backend code for handling another file other than `config/config.default.json`, but the option does not seem to be exposed to the `cli.py` file, it would be nice to be able to select a personal config without worrying about it needing to be stashed and poped every time I would want to update the project

**Comment by maximumstock** [comment]
Should be fixed in https://github.com/maximumstock/poe-currency-flip-planner/commit/94815f3b2f12e2d24439983b64b0e23a55be8933
