### ISSUE TITLE
The specified config file path does not exist

### ISSUE THREAD

**Issue by dinzyuk** [maximumstock/poe-currency-flip-planner#297]
Followed install via both poetry and python methods (python requirements wasnt installing numpy by the way!)

Getting below error
Nothing changed, straight from install.
What am i missing here

PS C:\Users\Shadow\Desktop\flip\poe-currency-flip-planner> python .\cli.py --league heist                                                                             Traceback (most recent call last):
  File "C:\Users\Shadow\Desktop\flip\poe-currency-flip-planner\src\config\user_config.py", line 124, in from_file
    with open(file_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Shadow\\Desktop\\flip\\poe-currency-flip-planner\\src\\config/../../config/config.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Shadow\Desktop\flip\poe-currency-flip-planner\cli.py", line 97, in <module>
    user_config = UserConfig.from_file(config_file_path)
  File "C:\Users\Shadow\Desktop\flip\poe-currency-flip-planner\src\config\user_config.py", line 128, in from_file
    raise Exception("The specified config file path does not exist")
Exception: The specified config file path does not exist

**Comment by maximumstock** [comment]
Hey there, thank you for reaching out! I pushed a new release and the current master should be fixed now. Please let me know if you are having anymore trouble. Sorry for the inconvenience!

**Comment by dinzyuk** [comment]
Seems to be fixed, thanks!
