### ISSUE TITLE
Doesn't fetch offers for standard league

### ISSUE THREAD

**Issue by zeus121212** [maximumstock/poe-currency-flip-planner#303]
Hi,

It seems to be endlessly fetching offers for standard league without finding any?

**Comment by maximumstock** [comment]
Hey there,

it seems to work for me with the default configuration:

![image](https://user-images.githubusercontent.com/9075718/111065991-00adaf00-84bd-11eb-8ffe-418c6bdf37b6.png)

Can you specify what you were trying to do and what the exact problem was?

**Comment by zeus121212** [comment]
Hi,

I probably messed something up. I have no idea how to use python or
anything but i got to this. Sorry to bother you I'll keep fiddling with the
steps, see if it works. Thanks
[image: image.png]

**Comment by maximumstock** [comment]
No problem :)

**Comment by zeus121212** [comment]
I got it to work :)

**Comment by maximumstock** [comment]
I'm glad to hear that! If you have any suggestions to improve documentation feel free to reach out.

**Comment by zeus121212** [comment]
Hm I literally knew how to do none of this before I googled it. I had no
idea you could run stuff like this through CMD prompt lol. I literally
googled how to get a terminal on windows haha. So my suggestions would
probably be way too obvious to most folks. But here are the steps I took to
get it working,

Install Python (from their website- microsoft store gave me issues)

   - x64 version...
   - in the installer enable options 'install for all user, add python to
   PATH, and disable path length limit', other than those options you can use
   the default config to install pip,venv etc
   - install python only 1x if you forgot to enable the options above you
   have to delete it and reinstall- having 2 pythons installed creates problems

Install Git (from their website)
Type 'Manage app execution aliases' into windows search bar

   - turn off both the on/off switches for python

Run CMD prompt w/ administrator privileges (don't use windows powershell..
and you dont need vscode or w/e)
From here your steps began to work with a little changes (see red)
-Copy/paste/enter: git clone
https://github.com/maximumstock/poe-currency-flip-planner.git
-Copy/paste/enter: cd poe-currency-flip-planner

   1. Enter a new shell session environment settings: py -m venv env


   - this change i guess has something to do with what i did in manage app
   execution aliases/ how windows does things iuno


   1. Activate your virtual environment: .\env\Scripts\activate


   - this change i guess, it's obvs to ppl that you don't need to type
   source?

Now for the next step I constantly had issues with the dependencies not
running in the venv, although when I ran the pip install -r
requirements.txt it would show all of them being satisfied. If I tried to
initiate the script it would say module numpy not found. So if i manually
installed that within the venv it would just point to another module not
being found. So I just installed all the dependencies outside of the venv
in another cmd prompt window. Apparently this is not ideal for w/e reason
but this is my personal comp so w/e I reformat it all the time anyway.

Then finally you can run cli.py --league "w/e league". Well i think i ran
into a windows permission issue here in not being allowed to run scripts
but i just googled it and found some line i could write into cmd prmpt to
give me the permission. I think i ran into the user permission thing a
couple times and just googled it and some forum would have a line i could
enter to get past it.

**Comment by maximumstock** [comment]
Ahh, I see, sounds like regular Python foo to me. It's not the easiest to setup, sadly :) I'll see what I can do, thank you for your answer!
