### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy'`

### ISSUE THREAD

**Issue by Nodrof** [maximumstock/poe-currency-flip-planner#316]
Hi,

Used:
`git clone https://github.com/maximumstock/poe-currency-flip-planner.git`
`cd poe-currency-flip-planner`
and
`python3 -m venv env`
`source ./env/bin/activate`
`pip install -r requirements.txt`

All requirments installed, did run pip install again to check and all says `Requirement already satisfied`.

Running `python cli.py --help`

Returns:
`(env) nodrof@Main:~/git/poe-currency-flip-planner$ python cli.py --help
Traceback (most recent call last):
  File "/home/nodrof/git/poe-currency-flip-planner/cli.py", line 6, in <module>
    from src.commands.pathfinder import execute_pathfinding
  File "/home/nodrof/git/poe-currency-flip-planner/src/commands/pathfinder.py", line 2, in <module>
    from src.commons import unique_conversions_by_trader_name
  File "/home/nodrof/git/poe-currency-flip-planner/src/commons.py", line 4, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'`

Nead help with what I could do. :)

Best reg
//Nodrof

**Comment by maximumstock** [comment]
Sorry for the inconvenience, please try to fetch master and reinstall the dependencies via `pip install -r requirements.txt` again.

**Comment by Nodrof** [comment]
If I was more skilled I could prolly solve it so Im greatfull for your efforts.

Wiped it and started over.
When I run `pip install -r requirements.txt` it gives this error. ->
`ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    typing-extensions>=3.6.5 from https://files.pythonhosted.org/packages/05/e4/baf0031e39cf545f0c9edd5b1a2ea12609b7fcba2d58e118b11753d68cf0/typing_extensions-4.0.1-py3-none-any.whl#sha256=7f001e5ac290a0c0401508864c7ec868be4e701886d5b573a9528ed3973d9d3b (from aiohttp==3.7.4.post0->-r requirements.txt (line 1))`

If I fetch typing-extensions with `pip install typing-extensions==3.10.0.2` and then run
`python cli.py --help` it still gives:
`$ python cli.py --help
Traceback (most recent call last):
  File "/home/nodrof/git/poe-currency-flip-planner/cli.py", line 6, in <module>
    from src.commands.pathfinder import execute_pathfinding
  File "/home/nodrof/git/poe-currency-flip-planner/src/commands/pathfinder.py", line 2, in <module>
    from src.commons import unique_conversions_by_trader_name
  File "/home/nodrof/git/poe-currency-flip-planner/src/commons.py", line 4, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'`

pip installed numpy and run `python cli.py --nelp` and added what gave error after so added
`numpy
jsonpickle
marshmallow` but then `pip install aiohttp` didnt work. Seems like `pip install -r requierments` halts after typing-extensions?

Will try to run it withou the hashes and see I if I get around it.

**Comment by Nodrof** [comment]
After I deleted all hash and trailing \ it went smooth.

`Successfully installed aiohttp-3.7.4.post0 aiolimiter-1.0.0 argon2-cffi-21.1.0 astroid-2.8.4 async-timeout-3.0.1 asyncio-3.4.3 attrs-20.3.0 autopep8-1.5.7 backcall-0.2.0 beautifulsoup4-4.10.0 bleach-4.1.0 cattrs-1.8.0 certifi-2021.10.8 cffi-1.15.0 chardet-4.0.0 charset-normalizer-2.0.7 coverage-6.0.2 cycler-0.11.0 debugpy-1.5.1 decorator-5.1.0 defusedxml-0.7.1 deserialize-1.8.3 entrypoints-0.3 flake8-3.9.2 idna-3.3 iniconfig-1.1.1 ipykernel-6.4.2 ipython-7.28.0 ipython-genutils-0.2.0 isort-5.9.3 jedi-0.18.0 jinja2-3.0.2 jsonpickle-1.5.2 jsonschema-4.1.2 jupyter-client-7.0.6 jupyter-core-4.9.1 jupyterlab-pygments-0.1.2 kiwisolver-1.3.2 lazy-object-proxy-1.6.0 markupsafe-2.0.1 marshmallow-3.14.0 matplotlib-3.4.3 matplotlib-inline-0.1.3 mccabe-0.6.1 mistune-0.8.4 multidict-5.2.0 mypy-0.790 mypy-extensions-0.4.3 nbclient-0.5.4 nbconvert-6.2.0 nbformat-5.1.3 nest-asyncio-1.5.1 notebook-6.4.5 numpy-1.21.1 packaging-21.0 pandas-1.1.5 pandocfilters-1.5.0 parso-0.8.2 pexpect-4.8.0 pickleshare-0.7.5 pillow-8.4.0 platformdirs-2.4.0 pluggy-1.0.0 prometheus-client-0.12.0 prompt-toolkit-3.0.21 ptyprocess-0.7.0 py-1.11.0 pycodestyle-2.7.0 pycparser-2.20 pyflakes-2.3.1 pygments-2.10.0 pylint-2.11.1 pyparsing-3.0.3 pyrsistent-0.18.0 pytest-6.2.5 pytest-cov-2.12.1 python-dateutil-2.8.2 pytz-2021.3 pyzmq-22.3.0 requests-2.26.0 rope-0.18.0 scipy-1.6.1 send2trash-1.8.0 six-1.16.0 soupsieve-2.2.1 terminado-0.12.1 testpath-0.5.0 toml-0.10.2 tornado-6.1 tqdm-4.62.3 traitlets-5.1.1 typed-ast-1.4.3 urllib3-1.26.7 wcwidth-0.2.5 webencodings-0.5.1 wrapt-1.13.2 yapf-0.30.0 yarl-1.7.0`

And seems to work. If you want me to test from scratch just msg and Ill do it.
Thx for your efforts. :)

**Comment by maximumstock** [comment]
I pushed some changes that remove the hashes in `requirements.txt` altogether, so you don't have to. Please try one more time to `pip install -r requirements.txt` with the current `master` branch.

**Comment by Nodrof** [comment]
Got some ignoring infos but no errors and it runs.  
Removed and did  a new clone and it worked aswell.

Pasting the ignores FYI but its nothing that seems to brake anything so Im all goood.

`$ pip install -r requirements.txt
Ignoring appnope: markers 'platform_system == "Darwin" and python_version >= "3.7" and sys_platform == "darwin"' don't match your environment
Ignoring argcomplete: markers 'python_version < "3.8.0" and python_version >= "3.7"' don't match your environment
Ignoring atomicwrites: markers 'python_version >= "3.6" and python_full_version < "3.0.0" and sys_platform == "win32" and (python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and python_version >= "3.6") or sys_platform == "win32" and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and python_version >= "3.6") and python_full_version >= "3.4.0"' don't match your environment
Ignoring cffi: markers 'implementation_name == "pypy" and python_version >= "3.6"' don't match your environment
Ignoring colorama: markers 'python_version >= "3.7" and python_full_version < "3.0.0" and platform_system == "Windows" and sys_platform == "win32" and (python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and python_version >= "3.6") and python_version < "4.0" or python_full_version >= "3.5.0" and platform_system == "Windows" and sys_platform == "win32" and python_version >= "3.7" and (python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and python_version >= "3.6") and python_version < "4.0"' don't match your environment
Ignoring importlib-metadata: markers 'python_version == "3.7" and python_full_version >= "3.6.1" and python_full_version < "4.0.0" and (python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and python_version >= "3.6") and (python_version >= "3.6" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.5.0" and python_version < "3.8" and python_version >= "3.6")' don't match your environment
Ignoring py: markers 'python_version >= "3.6" and python_full_version < "3.0.0" and implementation_name == "pypy" or python_full_version >= "3.5.0" and python_version >= "3.6" and implementation_name == "pypy"' don't match your environment
Ignoring pywin32: markers 'sys_platform == "win32" and platform_python_implementation != "PyPy" and python_version >= "3.6"' don't match your environment
Ignoring pywinpty: markers 'os_name == "nt" and python_version >= "3.6"' don't match your environment
Ignoring typed-ast: markers 'implementation_name == "cpython" and python_version < "3.8" and python_version >= "3.6"' don't match your environment
Ignoring typing-extensions: markers 'python_version >= "3.6" and python_version < "3.8"' don't match your environment
Ignoring zipp: markers 'python_version < "3.8" and python_version >= "3.6"' don't match your environment`

But Im up and running. :)

**Comment by maximumstock** [comment]
Great to hear! I'll keep an eye out for it, but it should not occur anymore. Thanks again for reaching out!
