### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by Ham5terzilla** [maximumstock/poe-currency-flip-planner#332]
Standart connection, win10, installed all from `requirements.txt`
Debug 
> (env) C:\games\poe flip>cli.py --debug
Using config file under C:\games\poe flip\config\config.default.json
Fetching Kalandra offers for 117 pairs
poetrade: Reschedule task: Chaos Orb -> Aetheric Fossil
Cannot connect to host currency.poe.trade:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)')]
poetrade: Reschedule task: Chaos Orb -> Ancient Orb
Cannot connect to host currency.poe.trade:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)')]
poetrade: Reschedule task: Chaos Orb -> Awakened Sextant
Cannot connect to host currency.poe.trade:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)')]
poetrade: Reschedule task: Jeweller's Orb -> Blessed Orb
Cannot connect to host currency.poe.trade:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)')]
poetrade: Reschedule task: Aetheric Fossil -> Chaos Orb
Cannot connect to host currency.poe.trade:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)')]
poetrade: Reschedule task: Awakened Sextant -> Chaos Orb
Cannot connect to host currency.poe.trade:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)')]
poetrade: Reschedule task: Blessed Orb -> Chaos Orb
Cannot connect to host currency.poe.trade:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)')]
poetrade: Reschedule task: Cartographer's Chisel -> Chaos Orb
Cannot connect to host currency.poe.trade:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)')]
poetrade: Reschedule task: Chromatic Orb -> Chaos Orb
Cannot connect to host currency.poe.trade:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)')]
poetrade: Reschedule task: Divine Orb -> Chaos Orb
Cannot connect to host currency.poe.trade:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)')]
Backend poetrade failed

**Comment by maximumstock** [comment]
I think this should be resolved by now as it looks like a temporarily expired certificate on poe.trade and it seems to work again. Thank you for reporting though 👍🏻
