### ISSUE TITLE
Installing on windows gives a bunch of errors

### ISSUE THREAD

**Issue by manweCZ** [maximumstock/poe-currency-flip-planner#338]
Hello,
Im not working with Python much so I have no idea what should I do - there is a ton of output below that...

`
Installing build dependencies: started                                                      
Installing build dependencies: finished with status 'done'                                  
Getting requirements to build wheel: started                                                
Getting requirements to build wheel: finished with status 'done'                            
Preparing metadata (pyproject.toml): started                                                
Preparing metadata (pyproject.toml): finished with status 'done'                            
ilding wheels for collected packages: typed-ast                                             
Building wheel for typed-ast (pyproject.toml): started                                      
Building wheel for typed-ast (pyproject.toml): finished with status 'error'                 
error: subprocess-exited-with-error                                                         
                                                                                            
Building wheel for typed-ast (pyproject.toml) did not run successfully.                     
exit code: 1                                                                                
                                                                                            
[101 lines of output]                                                                       
running bdist_wheel                                                                         
running build                                                                               
running build_py                                                                            
creating build                                                                              
creating build\lib.win-amd64-cpython-310                                                    
creating build\lib.win-amd64-cpython-310\typed_ast                                          
copying typed_ast\ast27.py -> build\lib.win-amd64-cpython-310\typed_ast                     
copying typed_ast\ast3.py -> build\lib.win-amd64-cpython-310\typed_ast                      
copying typed_ast\conversions.py -> build\lib.win-amd64-cpython-310\typed_ast               
copying typed_ast\__init__.py -> build\lib.win-amd64-cpython-310\typed_ast                  
creating build\lib.win-amd64-cpython-310\typed_ast\tests                                    
copying ast3\tests\test_basics.py -> build\lib.win-amd64-cpython-310\typed_ast\tests        
running build_ext                                                                           
building '_ast27' extension                                                                 
creating build\temp.win-amd64-cpython-310                                                   
creating build\temp.win-amd64-cpython-310\Release                                           
creating build\temp.win-amd64-cpython-310\Release\ast27                                     
creating build\temp.win-amd64-cpython-310\Release\ast27\Custom                              
creating build\temp.win-amd64-cpython-310\Release\ast27\Parser                              
creating build\temp.win-amd64-cpython-310\Release\ast27\Python                             
 `

and there is a bunch of Microsoft Visual Studio build tools errors below that. Any idea what could be wrong? Tried Googling but it seems like a general error so its impossible for me to find out what's really the problem

**Comment by maximumstock** [comment]
Hey there, sorry for my late reply and thank you for reaching out!

I've pushed some changes to `master` that should allow you to install just fine now. This project now requires Python 3.8, but if you use `poetry`, all should be taken care of automatically. Let me know if you encounter any more installation problems.

On another note, with `poe.trade` being closed down now and the official trading website requiring authentication by default, this project is currently in a non-working state. I'll focus on bringing up my own indexer in the meantime ([tracking issue](https://github.com/maximumstock/poe-stash-indexer/issues/244)) and will add it as a backend to this project ASAP. In the meantime, this tool is not working anymore.
