### ISSUE TITLE
Try to run and understend how i can help do its work

### ISSUE THREAD

**Issue by PavelKuratovDSone** [maximumstock/poe-currency-flip-planner#341]
Its loks like that its must work, but its stuck on "Fetching Sanctum offers for 117 pairs"... if you already get nick name and id you can do auth what problem?

**Comment by PavelKuratovDSone** [comment]
I think its realy intersing idea to create smth like this

**Comment by maximumstock** [comment]
Hey @PavelKuratovDSone, sorry for the late reply. Most likely the requests are timing out, since poe.trade was closed and the address unavailable. Sadly, this project is not really usable anymore as of now.
