### ISSUE TITLE
Compare data fetching speed of backend implementations

### ISSUE THREAD

**Issue by maximumstock** [maximumstock/poe-currency-flip-planner#5]
Currently, poe.trade supports a much higher fetching concurrency than pathofexile.com/trade (5 requests per 5 seconds). However, the latter seems to filter out (some) obvious price-fixing offers, which is not the case for poe.trade.

If poe.trade supports a considerable speedup compared to pathofexile.com/trade, it might be efficient to use the former, while adding some way to filter out price-fixing offers locally.

**Comment by ikelso** [comment]
I think the work you're doing to filter out specific traders would suffice here.  Keeping it as a text file would make it extremely simple and customizable to the user, but if you wanted to go a step further, a publicly available maintained list could be published at an endpoint that this project could query, and then fall back to a manual list if the public one isn't available.  

Alternatively, there could be some logic used to filter the bogus listings. Perhaps taking all the listings fetched, finding a median ratio, and then filtering out anything that's x% off that ratio?

**Comment by maximumstock** [comment]
@ikelso Having a global, curated list of price-fixers to avoid is definitely a good idea and already noted as a next step 👍 

I haven't really looked into a statistical filter yet, but you are basically right.

**Comment by maximumstock** [comment]
Current state:

- poe.trade backend is waaay faster and practically the only way to support the basic idea of this tool
- poeofficial API rate limit just makes anything non-trivial impossible
- deprecating the official pathofexile.com/trade API seems right
