### ISSUE TITLE
Configurable bounds (per item) for trade volume

### ISSUE THREAD

**Issue by maximumstock** [maximumstock/poe-currency-flip-planner#54]
## Background
We need some kind of interface to configure how much of a given currency should be tradable for a given session/graph query in order to...

1. avoid trades that go over the respective character inventory capacity (eg. 12x5x10 for Chaos Orbs)
2. avoid generating trading paths which a user does not have the amount of currency for

## Initial Idea

* [x] Add way to respect maximum stack sizes per item
  * [x] Add a new file that specifies maximum stack sizes per currency/item
  * [x] Have some generic class as interface to it
  * [x] Incorporate maximum stack sizes when finding conversions
* [x] Add way to configure minimum/maximum stock sizes
  * [x] Config file `config/config.json` with suitable format
  * [x] Need a robust parser for the format
  * [x] Incorporate minimum/maximum stock sizes when finding conversions
* [x] Limit conversion size based on available item capital
  * [x] Let user specify assets in config.json
  * [x] Incorporate asset specs when finding conversions
* [x] Derive pair filter from config file
* [ ] Add proper documentation

**Comment by maximumstock** [comment]
- Config file format
  - YAML seems superior than JSON as a configuration file format, as it supports comments by default and produces less clutter
  - Need to find configuration patterns first before deciding on a final format
- How should the `pair_filter` functionality be configured?
  - Currently, I have only limited experience how these filters might look
  - Should probably do some more data analysis over last few league's data to see which item pairs usually produce good value
  - Based on that we can see which format is more suitable

**Comment by HiPoEGH** [comment]
If your looking to add a GUI into the project at a later date, instead of using and outputting to CLI, then the best example I can think of is this project: https://sourceforge.net/projects/poe-trade-finder/

The project however is no longer maintained, but should still run fine.

I don't know why, but it's incredibly slow by comparison. Because it tries to rebuild the GUI display each update, and there are MANY trade requests to parse.
It has the limitation of not being able to specify minimum stocks, and searches for every single possible exchange if you have that item checked.

It would be nice to have a similar interface, so we can automatically copy a trade message with a button.

However making a GUI into the project is probably a significant task in itself.

**Comment by maximumstock** [comment]
> If your looking to add a GUI into the project at a later date, instead of using and outputting to CLI, then the best example I can think of is this project: https://sourceforge.net/projects/poe-trade-finder/
> 
> The project however is no longer maintained, but should still run fine.
> 
> I don't know why, but it's incredibly slow by comparison. Because it tries to rebuild the GUI display each update, and there are MANY trade requests to parse.
> It has the limitation of not being able to specify minimum stocks, and searches for every single possible exchange if you have that item checked.
> 
> It would be nice to have a similar interface, so we can automatically copy a trade message with a button.
> 
> However making a GUI into the project is probably a significant task in itself.

Not for now, but I do have plans to work on this. So far I plan on having this as a website with a shared graph backend which every use can query in real-time.

**Comment by maximumstock** [comment]
Here is my current config file format proposal

```jsonc
{
  "version": 1,
  "items": {
    "Chaos Orb": {
      "minimum_stock": 40,
      "maximum_stock": 500,
      "sell_for": {
        "Cartographer's Chisel": null,
        "Chromatic Orb": null,
        "Divine Orb": null,
        "Orb of Alchemy": null,
        "Orb of Regret": null,
        "Exalted Orb": null
      }
    },
    "Exalted Orb": {
      // If we want to buy Exalted Orbs, we only consider 
      // sellers with a stock between 1-100
      "minimum_stock": 1, // Defaults to 1
      "maximum_stock": 100, // Defaults to 0 (no limit)
      "sell_for": {
        "Cartographer's Chisel": null,
        // As there is no special config for Chaos Orbs,
        // we only consider sellers with a Chaos Orb stock
        // of 40-500
        "Chaos Orb": null,
        "Orb of Alchemy": null,
        "Orb of Alteration": null,
        "Orb of Annulment": {
          // If we want to buy Annulment Orbs with Exalted Orbs, we only 
          // consider sellers with a stock between 10-30
          "minimum_stock": 10,
          "maximum_stock": 30
        }
      }
    },
    "Orb of Annulment": {
      "minimum_stock": 1,
      "sell_for": {
        "Exalted Orb": 5
      }
    }
  }
}

```

**Comment by maximumstock** [comment]
Main functionality should be done now. The only thing that is missing is deriving the previous pair filter from your configuration file. However, min/max stock seller and trade volume filtering works afaics. 

@HiPoEGH  If you are interested, you can check out the respective [feature branch](https://github.com/maximumstock/poe-currency-flip-planner/tree/feat/configurable-maximum-tradable-stock-per-currency) and test a little bit. The config file structure is not yet documented but barely differs from your proposal. Maybe you can already find some early bugs :)

I'll implement the derivation of item pairs to check for from the config file and update the docs accordingly. Maybe we can get some kind of release going for the upcoming season.

**Comment by maximumstock** [comment]
Done per https://github.com/maximumstock/poe-currency-flip-planner/releases/tag/0.2.0
