### ISSUE TITLE
slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by zombodotcom** [maximumstock/poe-currency-flip-planner#6]
```
Spent 10.8s finding paths
Traceback (most recent call last):
  File "cli.py", line 49, in <module>
    log_conversions(p.results, currency, limit)
  File "cli.py", line 10, in log_conversions
    for c in conversions[currency][:limit]:
TypeError: slice indices must be integers or None or have an __index__ method
```

Fixed by Changing 

https://github.com/maximumstock/poe-currency-flip-planner/blob/0506f9c512a2b2b97a27033a18b6bdf73da4b97d/cli.py#L10

```
def log_conversions(conversions, currency, limit):
    for c in conversions[currency][:limit]:
        log_conversion(c)
```

to
make the slice use an int. 
```
def log_conversions(conversions, currency, limit):
    for c in conversions[currency][:int(limit)]:
        log_conversion(c)

```

Ran with 

`python cli.py --limit 10 --league "Betrayal" --currency "Exalted Orb"`

**Comment by maximumstock** [comment]
@zombodotcom Fixed via https://github.com/maximumstock/poe-currency-flip-planner/commit/8ce345eae189e5fd14667749477b96a077aeafc1. Thanks for pointing that out 👍 I've actually got a few other cli nice-to-haves in another branch that I'll merge soon.
