### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by demetrzz** [maximumstock/poe-currency-flip-planner#66]
i have 0 experience with python and coding overall, maybe ive done something wrong while installing something but i had this issue while running cli.py:

PS C:\Users\Demetr> python C:\Users\Demetr\Desktop\poe\poe-currency-flip-planner-master\cli.py
Traceback (most recent call last):
  File "C:\Users\Demetr\Desktop\poe\poe-currency-flip-planner-master\cli.py", line 85, in <module>
    p = PathFinder(league, chosen_currencies, backend, excluded_traders,
  File "C:\Users\Demetr\Desktop\poe\poe-currency-flip-planner-master\src\pathfinder.py", line 52, in __init__
    self.pair_filter = load_pair_filter()
  File "C:\Users\Demetr\Desktop\poe\poe-currency-flip-planner-master\src\items.py", line 11, in load_pair_filter
    with open("assets/pair_filter.json", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'assets/pair_filter.json'

not sure what i was doing wrong, but i couldnt install pipenv and maybe its something to do with this, seemed to work fine tho after editing paths to "C:/Users/Demetr/Desktop/poe/poe-currency-flip-planner-master/assets/pair_filter.json" in 3 files

**Comment by maximumstock** [comment]
Ah yeah, this does not occur when using pipenv, because it likely sets the current working directory to the project root, so the file is found under the original path. But it's fine if you got it working with manual paths. However, you might have to re-do these changes whenever your local repository instance.
