### ISSUE TITLE
One user throws off the list

### ISSUE THREAD

**Issue by zombodotcom** [maximumstock/poe-currency-flip-planner#7]
is there a way to blacklist one trade by a user?

**Comment by maximumstock** [comment]
@zombodotcom No, not right now. What exactly do you mean by "throws off the list"? Can you post the trade here?

**Comment by zombodotcom** [comment]
ill try and repeat the error. but one user was the base case for around 20 trades. every trade involved that person as the start, and he would never respond to trades.

**Comment by maximumstock** [comment]
Good catch! This problem is known, but I simply haven't had the time yet to look into filtering out price-fixers. For the short term, I can add a filter that lets you ignore specific trader names based on a manually administered list.

**Comment by maximumstock** [comment]
@zombodotcom You can now add trader igns to `excluded_traders.txt` to filter unwanted player accounts (see https://github.com/maximumstock/poe-currency-flip-planner/pull/9/).
