### ISSUE TITLE
excluded_traders does not handle non-standard characters

### ISSUE THREAD

**Issue by ikelso** [maximumstock/poe-currency-flip-planner#72]
If you try to use russian characters in excluded_traders.txt you receive the following error:

Traceback (most recent call last):
  File "cli.py", line 83, in <module>
    excluded_traders = [x.strip() for x in f.readlines()]
  File "c:\users\byrdc\appdata\local\programs\python\python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 159: character maps to <undefined>

I assume this would happen with any non-standard unicode character such as korean characters as well.

**Comment by maximumstock** [comment]
Great catch! I've merged your PR.
